# 환경별로 설정 분리하기

# local, dev, production 공통
server:
  port: 8080

# 실행할 환경 지정 spring:profiles:active 옵션
spring:

  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root

  # Session
  session:
    store-type: redis
    redis:
      flush-mode: on_save