# 환경별로 설정 분리하기

# local, dev, production 공통
server:
  port: 8081

# 실행할 환경 지정 spring:profiles:active 옵션
spring:
  profiles:
    active: dev

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root

  # Session
  session:
    store-type: redis
    redis:
      flush-mode: on_save

---
spring:
  config:
    activate:
      on-profile: dev

  apiServer:
    protocol: http
    host: 127.0.0.1
    port: 8080

---
spring:
  config:
    activate:
      on-profile: prod

  apiServer:
    protocol: http
    host: 43.200.41.75
    port: 8080
